= hermes(1)

== Name

hermes - generate Hermes RPC client and server stubs


== Synposis

*hermes* [*-h*|*--help*] [*--version*] [*--cpp*] [*--fortran*] _file_ _..._


== Description

The *hermes* source code generator parses each _file_ and creates Hermes RPC
server skeleton and client stub source code for the language(s) indicated with
the *--cpp* and *--fortran* options.  Each _file_ must contain an interface
description, expressed in the Hermes Interface Description Language (IDL).

The source file(s) generated by *hermes* can be compiled and linked against
an interface implementation to create a server, or against client code that
calls methods in the server.

== Options

=== Languages

*--cpp*::
  Generate C++ header and source.

*--fortran*::
  Generate Fortran source.

=== Program Information

*-h, --help*::
  Display help text and exit.

*--version*::
  Display version information and exit.


== Example

The following command parses the `foo.hid` interface description file and
generates the C++ header and source files `foo.hpp` and `foo.cpp`.

----
hermes --cpp foo.hid
----


== Diagnostics

The *hermes* utility exits 0 on success and <0 if an error occurs.
